name: Semantic Release

on:
  workflow_dispatch:

jobs:
  do_release:
    name: Create new release candidate
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/next')
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install semantic-release
        run: |
          npm i -g \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/changelog \
            @semantic-release/exec \
            conventional-changelog-conventionalcommits

      - name: Execute semantic-release to create release candidate
        run: |
          semantic-release --debug
